name: CD-Engine

on:
  push:
    tags:
    - 'engine-v*'
  
env:
  PACKAGE_DIRECTORY: ${{ github.workspace }}/output

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.101
    - name: Restore dependencies
      working-directory: ./Engine
      run: dotnet restore

    - name: Set VERSION from git tag 
      run: |
        TAG=${{ github.ref_name }}
        echo tag name: ${TAG}
        echo "VERSION=${TAG#engine-v}" >> $GITHUB_ENV      # remove prefix 'engine-v'

    - name: Echo version
      run: |
        echo package version: ${VERSION}

    - name: Build
      working-directory: ./Engine
      run: |
        echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
        dotnet build --no-restore /p:Version=${VERSION} /p:FileVersion=${VERSION} /p:AssemblyVersion=${VERSION} -c Release

    - name: Test
      working-directory: ./Engine
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Pack
      working-directory: ./Engine
      run: dotnet pack --no-restore --no-build -p:PackageVersion=${VERSION} -p:SymbolPackageFormat=snupkg -p:PackageOutputPath=${{ env.PACKAGE_DIRECTORY }} -c Release

    - name: Push
      working-directory: ./Engine
      run: |
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Reejk.Just.ECS.${VERSION}.nupkg                --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}

    
